/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com
 @idle games : http://www.gityx.com
 @QQ Group : 627141737

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Achievement Gotten!": "成就达成！",
    "[stage] -": "[阶段] -",
    "[true] -": "[真理] -",
    "[date] -": "[日期] -",
    "[time] -": "[时间] -",
    ", by creating an issue": ", 通过创建问题",
    ", if to reset with enough Energy.": "，如果用足够的能量重置。",
    ". Reset current Structures and Energy. Will also boost production by": ". 重置当前结构和能量。 还将提高产量",
    "(10 minutes worth of production)": "（10 分钟的制作价值）",
    "(before Accretion boost)": "（吸积提升前）",
    "Accretion": "吸积",
    "Advanced": "先进的",
    "All OFF": "全部关闭",
    "All ON": "全开",
    "and maybe more": "也许更多",
    "Arrow down and Arrow up -": "向下箭头和向上箭头 -",
    "Arrow left and Arrow right: (None/Shift)": "向左箭头和向右箭头：（无/Shift）",
    "Atoms": "原子",
    "Auto consume offline storage": "自动消耗离线存储",
    "Auto OFF": "自动关闭",
    "Auto ON": "自动开启",
    "Black holes:": "黑洞：",
    "Cancel": "取消",
    "cancel close Alert": "取消关闭警报",
    "Case sentitive": "区分大小写",
    "Change Active Stage": "更改活动阶段",
    "change subtab": "更改子标签",
    "Change tab": "更改选项卡",
    "Check": "查看",
    "Collapse": "坍塌",
    "Collapse when can increase Mass at least": "塌陷时至少可以增加质量",
    "Confirm": "确认",
    "confirm close Alert": "确认关闭警报",
    "Confirmation toggles": "确认切换",
    "Consuming": "消费",
    "Cosmic dust production hardcap starts at": "宇宙尘埃生产硬帽开始于",
    "Cost:": "成本：",
    "Current Active Stages": "当前活动阶段",
    "Current effect -> after Collapse": "当前效果 -> 折叠后",
    "Current stage:": "当前阶段：",
    "Current tab is stage tab": "当前选项卡是阶段选项卡",
    "Current tab: Stage tab": "当前选项卡：阶段选项卡",
    "Custom font size (art won't scale)": "自定义字体大小（艺术不会缩放）",
    "Delete save file": "删除存档",
    "Description:": "描述：",
    "Discharge": "释放",
    "Discharge goals:": "出院目标：",
    "Discord": "不和谐",
    "Effect:": "影响：",
    "Element:": "元素：",
    "Elements": "元素",
    "Energy": "能量",
    "Enter -": "进入 -",
    "Escape -": "逃脱 -",
    "Export save file": "导出保存文件",
    "false": "错误的",
    "for current active Stage": "当前活动阶段",
    "for current day, month, year": "当前日、月、年",
    "for current hour, minute, second": "当前时、分、秒",
    "for current true Stage": "对于当前的真实阶段",
    "For every reached Milestone, will earn": "对于每个达到的里程碑，将获得",
    "Format type:": "格式类型：",
    "from Offline storage to add": "从离线存储添加",
    "Fundamental.": "基本原理。",
    "Fundamental.txt": "基础.txt",
    "Gain": "获得",
    "Game autosave interval": "游戏自动保存间隔",
    "Game is loading. If it won't load, then can try to report it": "游戏正在加载。 如果它不会加载，那么可以尝试报告它",
    "here": "这里",
    "Hide": "隐藏",
    "Highest Main-sequence mass:": "最高主序质量：",
    "Highest:": "最高：",
    "Hover to see.": "悬停查看。",
    "If you do not need Screen Reader support, then turn it off in settings": "如果您不需要屏幕阅读器支持，请在设置中将其关闭",
    "Information for Strange quarks": "奇异夸克的信息",
    "Intergalactic": "星际",
    "Interstellar": "星际",
    "Language type hotkeys (English only)": "语言类型热键（仅限英文）",
    "Last time saved:": "上次保存时间：",
    "Less recommended options": "较少推荐的选项",
    "Load": "加载",
    "Lose all progress, but move to the next stage. Each stage has its own unique theme.": "失去所有进展，但进入下一阶段。 每个阶段都有自己独特的主题。",
    "Main-sequence mass gain is limited to": "主序质量增益限于",
    "make a new Structure": "做一个新的结构",
    "Matter": "物质",
    "Max export:": "最大导出：",
    "Max offline:": "最大离线：",
    "Microworld": "微观世界",
    "Missing": "失踪",
    "Mobile device support": "移动设备支持",
    "Molecules": "分子",
    "Most Clouds at once:": "一次最多的云：",
    "Most Energy at once:": "一次最多的能量：",
    "ms": "多发性硬化症",
    "Need:": "需要：",
    "Need: 24 Particles": "需要：24 个粒子",
    "Need: 3 Atoms": "需要：3个原子",
    "Need: Missing": "需要：失踪",
    "Neutron stars:": "中子星：",
    "Next goal is 1 Energy": "下一个目标是 1 能量",
    "Next:": "下一个：",
    "Not in current session": "不在当前会话中",
    "Numbers -": "数字 -",
    "Numbers update and auto speed interval": "数字更新和自动速度间隔",
    "obtain on Stage reset:": "获得舞台重置：",
    "Options": "选项",
    "or any Star reward by": "或任何星级奖励",
    "Particles": "粒子",
    "Pause game": "暂停游戏",
    "Placeholder": "占位符",
    "Please export save file regularly": "请定期导出存档",
    "point": "观点",
    "Preons production hardcap starts at": "Preons 生产硬帽开始于",
    "Preview": "预览",
    "producing": "生产",
    "Quarks": "夸克",
    "Rank": "段位",
    "Red giants:": "红巨人：",
    "Requirement:": "要求：",
    "Research": "研究",
    "Researches": "研究",
    "Resource.": "资源。",
    "Return back to Microworld if can get at least": "如果至少能得到，就返回微观世界",
    "Reward:": "报酬：",
    "Screen reader support": "屏幕阅读器支持",
    "Select different theme from here": "从这里选择不同的主题",
    "Self-made Stars:": "自制明星：",
    "separator": "分隔器",
    "Special Researches": "专项研究",
    "Stage": "阶段",
    "Stage resets:": "阶段重置：",
    "Stage:": "阶段：",
    "Started playing:": "开始播放：",
    "Stats": "统计数据",
    "Storaged offline:": "离线存储：",
    "Strange matter": "奇怪的事情",
    "Strange quark.": "奇怪的夸克。",
    "Strange quarks": "奇夸克",
    "Strange quarks for doing it": "这样做的奇怪夸克",
    "Strange quarks:": "奇异夸克：",
    "Strange quarks.": "奇怪的夸克。",
    "Strangeness": "陌生感",
    "Strict": "严格的",
    "Structures": "结构",
    "Submerged": "湮",
    "Support isn't full, might have mistakes. If there are any mistakes or suggestions, you can contact me trough Discord (link in settings) or": "支持不完整，可能有错误。 如果有任何错误或建议，您可以通过 Discord（设置中的链接）或",
    "This reset:": "此重置：",
    "times": "次",
    "times of a current amount": "当前数量的倍数",
    "to passed time": "过去的时间",
    "To switch Active Stage, press Shift + Left or Right Arrow": "要切换活动舞台，请按 Shift + 向左或向右箭头",
    "Total improvement:": "总体改进：",
    "Total:": "全部的：",
    "Type:": "类型：",
    "Unlock:": "开锁：",
    "Unlocked Ranks:": "解锁等级：",
    "Unlocks:": "解锁：",
    "Upgrades": "升级",
    "Use left or right arrow keys to navigate through tabs. Up or down arrows to navigate through subtabs (when there are any). Can check other hotkeys in settings.": "使用向左或向右箭头键浏览选项卡。 向上或向下箭头在子选项卡中导航（如果有的话）。 可以在设置中查看其他热键。",
    "Vacuum state:": "真空状态：",
    "Vaporization": "汽化",
    "Vaporize when can get at least": "蒸发时至少可以得到",
    "Version": "版本",
    "Visual game update interval": "视觉游戏更新间隔",
    "Visual numbers update interval": "视觉数字更新间隔",
    "Void": "空白",
    "Warp": "经",
    "Welcome back": "欢迎回来",
    "You are not ready": "你还没准备好",
    "You can add any of these for extra information of a save file": "您可以添加其中任何一个以获得保存文件的额外信息",
    "Show": "显示",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    // 图标代码，不能汉化
    "Jacorb's Games": "Jacorb's Games",
    "Github": "Github",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "By Jacorb90": "By Jacorb90",
    "content_copy": "content_copy",
    "library_books": "library_books",
    "discord": "discord",
    "drag_handle": "drag_handle",
    "edit": "edit",
    "forum": "forum",
    "content_paste": "content_paste",
    "delete": "delete",
    "info": "info",
    "settings": "settings",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    'x': 'x',
    'QQ群号:': 'QQ群号:',
    '* 启用后台游戏': '* 启用后台游戏',
    '更多同类游戏:': '更多同类游戏:',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀
var cnPrefix = {
    "\n": "\n",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": "",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示：",
    "Welcome to 'Fundamental'.\nThis is a test-project made by awWhy. Should be supported by modern browsers, phones and screen readers (need to turn support ON in settings).\nWas inspired by 'Synergism', 'Antimatter Dimensions' and others.\nCurrent version is ": "欢迎来到“Fundamental”。\n这是 awWhy 制作的测试项目。 应受现代浏览器、手机和屏幕阅读器的支持（需要在设置中打开支持）。\n灵感来自“Synergism”、“Antimatter Dimensions”等。\n当前版本为 ",
    "Make for: ": "成本：",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀
var cnPostfix = {
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "  ",
    " ": " ",
    "\n": "\n",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+)$/,
    /^([\d\.]+)e(\d+)$/,
    /^([\d\.]+)$/,
    /^\(([\d\.]+)\)$/,
    /^([\d\.]+)\%$/,
    /^([\d\.]+)\/([\d\.]+)$/,
    /^\(([\d\.]+)\/([\d\.]+)\)$/,
    /^成本(.+)$/,
    /^\(([\d\.]+)\%\)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)K$/,
    /^([\d\.]+)M$/,
    /^([\d\.]+)B$/,
    /^([\d\.]+) K$/,
    /^([\d\.]+) M$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^\+([\d\.,]+)$/,
    /^\-([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^([\d\.,]+) \/ ([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^e([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Welcome back, you were away for (.+) seconds.\nCurrent version is (.+)$/, '欢迎回来，您离开了 $1 秒。\n当前版本是 $2'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m$/, '$1天 $2小时 $3分'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^([\d\.,]+) seconds ago$/, '$1 秒前'],
    [/^([\d\.,]+) Quarks$/, '$1 夸克'],
    [/^([\d\.,]+) hours$/, '$1 小时'],
    [/^([\d\.,]+) seconds$/, '$1 秒'],
    [/^\+([\d\.,]+) seconds$/, '+$1 秒'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Need: (.+) Quarks$/, '需要：$1 夸克'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) elves$/, '要求：$1 精灵'],
    [/^Req: (.+) \/ (.+) elves$/, '要求：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);